version: '3.7'

services:

  pedidos:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile-dev
    volumes:
      - './services/pedidos:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_dev  # nuevo
      - DATABASE_TEST_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_test  # nuevo
    depends_on: # nuevo
      - pedidos-db

  pedidos-db: # nuevo
    build:
      context: ./services/pedidos/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - pedidos
  #admin:
    #image:  portainer/portainer:latest
    #container_name: admin
    #command: --no-auth
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /srv/docker/portainer:/data
    #ports:
      #- 12345:9000



